CREATE DATABASE cms DEFAULT CHARACTER SET utf8;
USE cms;
CREATE TABLE article(
  id INT NOT NULL AUTO_INCREMENT UNIQUE,
  title VARCHAR(255),
  content TEXT CHARACTER SET utf8,
  published_at DATETIME,
  PRIMARY KEY(id)
);